import React from 'react'
import {
  LayoutDashboard, House, Building2, Building, User, Users, UserRound, FileSignature,
  CreditCard, Receipt, FileText, FolderArchive, Wrench, BarChart3, Settings,
  HardHat, CheckCircle2, Check, CircleSlash, Clock, Flame, TriangleAlert,
  AlertCircle, Info, Plus, Pencil, Trash2, Search, RefreshCw, X, Eye, Download,
  Upload, ExternalLink, Link2, Copy, Filter, ArrowUpDown, Maximize2, Minimize2,
  ZoomIn, ZoomOut, RotateCcw, Wallet, Euro, Banknote, TrendingUp, PieChart,
  Calculator, PiggyBank, DraftingCompass, Ruler, Folder, FolderOpen, File,
  FileSpreadsheet, Image, Camera, Paperclip, Mail, Send, Phone, Calendar,
  MapPin, Map, Globe, Square, DoorClosed, BedDouble, Bath, Trees, Zap,
  KeyRound, Lock, Unlock, ShieldCheck, Wifi, Thermometer, Droplets, HelpCircle,
  Warehouse, Store, Sparkles, Bell, ChevronDown, ChevronRight, ChevronUp,
  ArrowRight, ArrowLeft, Percent, SlidersHorizontal, Layers, Activity,
  CheckSquare, CircleDollarSign, CircleDot, Kanban, Bookmark, EyeOff
} from 'lucide-react'

// Mapping direct et optimisé
const ICON_MAP = {
  // Navigation & Sections
  dashboard: LayoutDashboard,
  logement: House,
  logements: House,
  bien: House,
  biens: House,
  home: House,
  house: House,
  immeuble: Building2,
  building: Building,
  building2: Building2,
  projet: HardHat,
  projets: HardHat,
  carte: Map,
  map: Map,
  globe: Globe,
  locataire: User,
  locataires: Users,
  user: User,
  users: Users,
  proprietaire: UserRound,
  bail: FileSignature,
  baux: FileSignature,
  filesignature: FileSignature,
  edl: FileSignature,
  etatdeslieux: FileSignature,
  paiement: CreditCard,
  paiements: CreditCard,
  revenus: CreditCard,
  creditcard: CreditCard,
  depense: Receipt,
  depenses: Receipt,
  receipt: Receipt,
  pret: CircleDollarSign,
  prets: CircleDollarSign,
  loan: CircleDollarSign,
  rendement: TrendingUp,
  rendements: TrendingUp,
  simulation: Calculator,
  simulations: Calculator,
  document: FileText,
  documents: FolderArchive,
  folderarchive: FolderArchive,
  maintenance: Wrench,
  ticket: Wrench,
  wrench: Wrench,
  tache: CheckSquare,
  taches: CheckSquare,
  echeance: Clock,
  echeances: Clock,
  calendar: Calendar,
  analyse: BarChart3,
  analyses: BarChart3,
  rapport: BarChart3,
  rapports: BarChart3,
  barchart3: BarChart3,
  notification: Bell,
  notifications: Bell,
  bell: Bell,
  parametres: Settings,
  settings: Settings,

  // Types de biens & projets
  appartement: Building,
  maison: House,
  studio: DoorClosed,
  parking: Square,
  garage: Warehouse,
  warehouse: Warehouse,
  store: Store,
  local_commercial: Store,
  localcommercial: Store,
  terrain: Trees,
  trees: Trees,
  sparkles: Sparkles,
  chantier: HardHat,
  hardhat: HardHat,
  construction: HardHat,
  renovation: Wrench,
  amenagement: Sparkles,
  transformation: DraftingCompass,

  // Statuts & Badges
  actif: CheckCircle2,
  check: Check,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
  inactif: CircleSlash,
  circleslash: CircleSlash,
  attente: Clock,
  clock: Clock,
  urgent: Flame,
  flame: Flame,
  alert: TriangleAlert,
  alerte: TriangleAlert,
  warning: TriangleAlert,
  trianglealert: TriangleAlert,
  danger: AlertCircle,
  alertcircle: AlertCircle,
  info: Info,
  activity: Activity,
  dot: CircleDot,

  // Actions & Flèches
  plus: Plus,
  ajouter: Plus,
  edit: Pencil,
  modifier: Pencil,
  pencil: Pencil,
  trash: Trash2,
  trash2: Trash2,
  supprimer: Trash2,
  search: Search,
  recherche: Search,
  refresh: RefreshCw,
  refreshcw: RefreshCw,
  close: X,
  x: X,
  eye: Eye,
  eyeoff: EyeOff,
  download: Download,
  upload: Upload,
  externallink: ExternalLink,
  link: Link2,
  copy: Copy,
  filter: Filter,
  sort: ArrowUpDown,
  expand: Maximize2,
  collapse: Minimize2,
  zoomin: ZoomIn,
  zoomout: ZoomOut,
  reset: RotateCcw,
  chevrondown: ChevronDown,
  chevronright: ChevronRight,
  chevronup: ChevronUp,
  arrowright: ArrowRight,
  arrowleft: ArrowLeft,
  sliders: SlidersHorizontal,
  slidershorizontal: SlidersHorizontal,
  layers: Layers,
  kanban: Kanban,
  bookmark: Bookmark,
  percent: Percent,

  // Finances
  wallet: Wallet,
  finances: Wallet,
  euro: Euro,
  cash: Banknote,
  banknote: Banknote,
  chart: TrendingUp,
  trendingup: TrendingUp,
  piechart: PieChart,
  calculator: Calculator,
  piggybank: PiggyBank,

  // Documents & Plans
  plan: DraftingCompass,
  plans: DraftingCompass,
  draftingcompass: DraftingCompass,
  ruler: Ruler,
  folder: Folder,
  folderopen: FolderOpen,
  file: File,
  filetext: FileText,
  filespreadsheet: FileSpreadsheet,
  filepdf: FileText,
  fileimage: Image,
  camera: Camera,
  image: Image,
  paperclip: Paperclip,

  // Communication & Coordonnées
  mail: Mail,
  email: Mail,
  send: Send,
  phone: Phone,
  location: MapPin,
  mappin: MapPin,

  // Équipements
  surface: Square,
  room: DoorClosed,
  doorclosed: DoorClosed,
  bedroom: BedDouble,
  beddouble: BedDouble,
  bathroom: Bath,
  bath: Bath,
  tree: Trees,
  power: Zap,
  zap: Zap,
  energy: Zap,
  key: KeyRound,
  keys: KeyRound,
  keyround: KeyRound,
  lock: Lock,
  unlock: Unlock,
  shield: ShieldCheck,
  shieldcheck: ShieldCheck,
  wifi: Wifi,
  thermometer: Thermometer,
  droplet: Droplets,
  droplets: Droplets,
  water: Droplets,
  gas: Flame,
}

export default function Icon({
  name,
  size = 16,
  color = 'currentColor',
  strokeWidth = 2,
  className = '',
  style = {},
  ...props
}) {
  const normalizedKey = String(name || '').toLowerCase().replace(/[-_]/g, '')
  const LucideComponent = ICON_MAP[name] || ICON_MAP[normalizedKey] || HelpCircle

  return (
    <span
      className={`app-icon ${className}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: size,
        height: size,
        flexShrink: 0,
        verticalAlign: 'middle',
        ...style
      }}
      aria-hidden="true"
      {...props}
    >
      <LucideComponent
        size={size}
        color={color}
        strokeWidth={strokeWidth}
        style={{ width: '100%', height: '100%' }}
      />
    </span>
  )
}
